### PR TITLE
Fixes for some small bugs

### PR DESCRIPTION
**Pull request by aocenas**
Hopefully should be self explanatory

### CODE REVIEW

**Comment by sunshinejr** [comment]
Thanks for the input 🎉

**Comment by aocenas** [comment]
@sunshinejr it seems like you reverted all these changes with commit 59ae6705c2b059879d7485773e7c1234bf6af058. Not sure if it was some merge error or not so just pointing it out.

**Comment by sunshinejr** [comment]
Whoops, my bad. But thanks to my bad, I checked once again one thing, and not animating `defaultSelectedIndex` may cause not selecting it at all (e.g. in `viewDidLoad()`). This issue is going on for some time and would need some investigation. Other than that, your changes are again in master, thanks again.

**Comment by sunshinejr** [comment]
I'm closing this one and I've opened a ticket for that issue #7.

**Pull request merged**
